In [1]:
import polars as pl 
import numpy as np 
import matplotlib.pyplot as plt 
import os
from tqdm import tqdm

In [5]:
df = pl.read_parquet("../data/ExportGridData_2026-05-19_130707032_FERRARI_13062024_FG.parquet")
df

shape: (481_798, 191)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRADEDATE ┆ HDR_TOPIC ┆ HDR_PARTI ┆ HDR_BATCH ┆ … ┆ STRATEGYL ┆ STRATEGYL ┆ STRATEGYL ┆ ROW_NUMB │
│ ---       ┆ ID        ┆ TIONID    ┆ ID        ┆   ┆ INK_SYMBO ┆ INK_EXECU ┆ INK_TRADE ┆ ER       │
│ datetime[ ┆ ---       ┆ ---       ┆ ---       ┆   ┆ LINDEX    ┆ TIONID    ┆ UNIQUEIDE ┆ ---      │
│ ns]       ┆ str       ┆ i64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ NTI…      ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 2        │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 3        │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 4        │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 5        │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 481794   │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 481795   │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 481796   │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 481797   │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ 2EQUFORD  ┆ 55        ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ 481798   │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df.columns

['TRADEDATE',
 'HDR_TOPICID',
 'HDR_PARTITIONID',
 'HDR_BATCHID',
 'HDR_MESSAGETYPE',
 'HDR_APPLKEYSEQUENCENUMBER',
 'HDR_OFFSETID',
 'HDR_FRAMESN',
 'HDR_HWMPRODUCERID',
 'HDR_HWMSEQUENCENUMBER',
 'MIC',
 'MARKETCODE',
 'EMM (*) (Tooltip)',
 'EMM (*)',
 'SYMBOLINDEX',
 'ISIN',
 'INSTRUMENTID',
 'INSTRUMENTGROUPCODE',
 'OFFICIALSEGMENT',
 'TRADINGCURRENCY',
 'HDR_RECEIVETIME',
 'PRODUCETIME',
 'CONSUMETIME',
 'EXECUTIONID',
 'FIRMID (*) (Tooltip)',
 'FIRMID',
 'EVENTID',
 'ORDEREVENTTYPE (*) (Tooltip)',
 'ORDEREVENTTYPE (*)',
 'ACCOUNTTYPEINTERNAL (*) (Tooltip)',
 'ACCOUNTTYPEINTERNAL (*)',
 'ACKPHASE (*) (Tooltip)',
 'ACKPHASE (*)',
 'ACKQUALIFIERS',
 'ACKTYPE (*) (Tooltip)',
 'ACKTYPE (*)',
 'BOOKIN',
 'BOOKOUTTIME',
 'CLIENTORDERID',
 'DARKINDICATOR',
 'DEFERREDTRADEINDICATOR',
 'DISPLAYEDORDERINTERACTION',
 'SWEEPORDERINDICATOR',
 'MINIMUMQUANTITYTYPE',
 'STPRESTINGORDER',
 'STPINCOMINGORDER',
 'DISCLOSEDQUANTITYRANDOMIZATION',
 'DISABLEDCANCELONDISCONNECTINDICATOR',
 'RFQANSWER',
 'RFQCONFIRMATION',
 'CONDITIONALORDER',
 'STPBOTHORDERS',
 'INDICATIVEAUCTIONPRICE',
 'INDICATIVEAUCTIONVOLUME',
 'OESESSIONID',
 'LPROLE (*) (Tooltip)',
 'LPROLE (*)',
 'DEAINDICATOR',
 'INVESTMENTALGOINDICATOR',
 'EXECUTIONALGOINDICATOR',
 'COMMODITYDERIVATIVEINDICATOR',
 'DEFERRALINDICATOR',
 'FRMARAMPLP',
 'OEGINFROMMEMBER',
 'OEGOUTTIMETOME',
 'ORDERID',
 'ORDERPRIORITY',
 'ORDERPX',
 'ORDERQTY',
 'ORDERSIDE (*) (Tooltip)',
 'ORDERSIDE (*)',
 'ORDERTYPE (*) (Tooltip)',
 'ORDERTYPE (*)',
 'ORIGCLIENTORDERID',
 'STPID',
 'TIMEINFORCE (*) (Tooltip)',
 'TIMEINFORCE (*)',
 'DISPLAYEDQTY',
 'CROSSORDERINDICATOR',
 'COUNTERPARTFIRMID',
 'EXECUTIONPHASE (*)',
 'LASTSHARES',
 'LASTTRADEDPX',
 'LEAVESQTY',
 'UNCROSSINGTRADE',
 'FIRSTTRADEPRICE',
 'PASSIVEORDER',
 'AGGRESSIVEORDER',
 'TRADECREATIONBYMARKETOPERATIONS',
 'NAVTRADEEXPRESSEDINBPS',
 'NAVTRADEEXPRESSEDINPRICECURRENCY',
 'DEFERREDPUBLICATION',
 'TRADETIME',
 'TRADETYPE (*) (Tooltip)',
 'TRADETYPE (*)',
 'KILLREASON (*) (Tooltip)',
 'KILLREASON (*)',
 'BREACHEDCOLLARPRICE',
 'COLLARREJTYPE (*)',
 'REJECTEDMESSAGE',
 'ERRORCODE (*) (Tooltip)',
 'ERRORCODE (*)',
 'STOPQUEUEPRIORITY',
 'COUNTERPARTYREASONTYPE (*)',
 'QUOTEINDICATOR',
 'QUOTEREQID',
 'LISTRANSACTIONID',
 'WHOLESALETRADETYPE (*)',
 'SEQUENCETIME',
 'LOGICALACCESSFLAGS_VALUE',
 'ORDERSTATUS',
 'AGGRESSIVEIMPLIED',
 'RANDOMGUARANTEEDMINIMUM',
 'ISSUINGORTENDEROFFERORDER',
 'RANDOMPRORATA',
 'ROUTED',
 'REGULATORDISPLAYEDQUANTITY',
 'ESCBMEMBERSHIP',
 'RFCID',
 'ISINITIATOR',
 'EXCHANGEIOIID',
 'TRADEUNIQUEIDENTIFIER',
 'FTS_FREETEXT',
 'ORDER_STOPPX',
 'ROUTINGSTRATEGY',
 'ORIGINALORDERTYPE (*) (Tooltip)',
 'ORIGINALORDERTYPE (*)',
 'ORDERTOLERABLEPRICE',
 'ORDERSWEEPREASON (*) (Tooltip)',
 'ORDERSWEEPREASON (*)',
 'ORDER_PEGOFFSET',
 'ORDER_UNDISCLOSEDPRICE',
 'ORDER_DISCLOSEDQTY',
 'ORDER_ORDEREXPIRATIONTIME',
 'ORDER_ORDEREXPIRATIONDATE',
 'ORDER_TRADINGSESSION',
 'ORDER_STOPTRIGGEREDTIMEINFORCE',
 'ORDER_UNDISCLOSEDICEBERGTYPE',
 'CLEARING_CLEARINGFIRMID',
 'CLEARING_CLIENTID',
 'CLEARING_ACCOUNTNUMBER',
 'CLEARING_TECHNICALORIGIN',
 'CLEARING_OPENCLOSE',
 'CLEARING_CLEARINGINSTRUCTION',
 'ORDER_TRADINGCAPACITY (*) (Tooltip)',
 'ORDER_TRADINGCAPACITY (*)',
 'ORDER_MINIMUMORDERQUANTITY',
 'ORDER_ACCOUNTTYPECROSS',
 'NMSC_ORIGINALCLIENTIDSHORTCODE',
 'NMSC_ORIGINALEXECWFIRMSHORTCODE',
 'NMSC_ORIGINALINVESTDECISWFIRMSHORTCODE',
 'NMSC_ORIGINALNONEXECBROKERSHORTCODE',
 'MSC_EVENTCLIENTIDSHORTCODE',
 'MSC_EVENTEXECWFIRMSHORTCODE',
 'CF_MARKETPHASEFLAG',
 'CF_MARGINTRADINGFLAG',
 'CF_ACCESSFLAG',
 'CF_TRADERID',
 'CF_SENDERLOCATIONID',
 'CF_DESKID',
 'MCIF_EVENTINVESTORID',
 'NMCIF_ORIGINALINVESTORID',
 'ECA_CLEARINGACCOUNT',
 'OFD_EVALUATEDPRICE',
 'OFD_MESSAGEPRICENOTATION',
 'OFD_FINALSYMBOLINDEX',
 'OFD_FINALEXECUTIONID',
 'AI_LONGCLIENTID',
 'SCDNM_ORIGINALSHORTCODETYPE_1',
 'SCDNM_SHORTCODEROLE_1',
 'SCDNM_SHORTCODEROLEQUALIFIER_1',
 'SCDNM_ORIGINALSHORTCODETYPE_2',
 'SCDNM_SHORTCODEROLE_2',
 'SCDNM_SHORTCODEROLEQUALIFIER_2',
 'SCDNM_ORIGINALSHORTCODETYPE_3',
 'SCDNM_SHORTCODEROLE_3',
 'SCDNM_SHORTCODEROLEQUALIFIER_3',
 'SCDNM_ORIGINALSHORTCODETYPE_4',
 'SCDNM_SHORTCODEROLE_4',
 'SCDNM_SHORTCODEROLEQUALIFIER_4',
 'SCDM_EVENTSHORTCODETYPE_1',
 'SCDM_SHORTCODEROLE_1',
 'SCDM_SHORTCODEROLEQUALIFIER_1',
 'SCDM_EVENTSHORTCODETYPE_2',
 'SCDM_SHORTCODEROLE_2',
 'SCDM_SHORTCODEROLEQUALIFIER_2',
 'STRATEGYLINK_ORDERSIDE',
 'STRATEGYLINK_SYMBOLINDEX',
 'STRATEGYLINK_EXECUTIONID',
 'STRATEGYLINK_TRADEUNIQUEIDENTIFIER',
 'ROW_NUMBER']

In [ ]:
keep_cols = [
        # instrument / session keys
        "TRADEDATE",
        "ISIN",
    
        # event ordering / timestamps
        "HDR_APPLKEYSEQUENCENUMBER",
        "HDR_HWMSEQUENCENUMBER",
        "HDR_OFFSETID",
        "SEQUENCETIME",
        "BOOKIN",
        "BOOKOUTTIME",
        "TRADETIME",
        "ROW_NUMBER",
    
        # event and order identity
        "EVENTID",
        "ORDEREVENTTYPE (*)",
        "TRADETYPE (*)",
        "ORDERSTATUS",
        "ORDERID",
        "ORDERPRIORITY",
        "CLIENTORDERID",
        "ORIGCLIENTORDERID",
        "EXECUTIONID",
        "TRADEUNIQUEIDENTIFIER",
    
        # order-book / trade mechanics
        "ORDERSIDE (*)",
        "ORDERPX",
        "ORDERQTY",
        "DISPLAYEDQTY",
        "LEAVESQTY",
        "LASTSHARES",
        "LASTTRADEDPX",
        "ORDERTYPE (*)",
        "TIMEINFORCE (*)",
        "KILLREASON (*)",
        "PASSIVEORDER",
        "AGGRESSIVEORDER",
    
        # agent / client / regulatory identity
        "NMSC_ORIGINALCLIENTIDSHORTCODE",
        "MSC_EVENTCLIENTIDSHORTCODE",
        "FIRMID",
        "NMSC_ORIGINALEXECWFIRMSHORTCODE",
        "MSC_EVENTEXECWFIRMSHORTCODE",
        "NMSC_ORIGINALINVESTDECISWFIRMSHORTCODE",
        "NMSC_ORIGINALNONEXECBROKERSHORTCODE",
        "ACCOUNTTYPEINTERNAL (*)",
        "LPROLE (*)",
        "ORDER_TRADINGCAPACITY (*)",
        "DEAINDICATOR",
        "INVESTMENTALGOINDICATOR",
        "EXECUTIONALGOINDICATOR",
    ]

df_filtered = df.select(keep_cols)
df_filtered

shape: (481_798, 46)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ TRADEDATE ┆ ISIN      ┆ HDR_APPLK ┆ HDR_HWMSE ┆ … ┆ DEAINDICA ┆ INVESTMEN ┆ EXECUTION ┆ FRMARAMP │
│ ---       ┆ ---       ┆ EYSEQUENC ┆ QUENCENUM ┆   ┆ TOR       ┆ TALGOINDI ┆ ALGOINDIC ┆ LP       │
│ datetime[ ┆ str       ┆ ENUMBER   ┆ BER       ┆   ┆ ---       ┆ CATOR     ┆ ATOR      ┆ ---      │
│ ns]       ┆           ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str      │
│           ┆           ┆ i64       ┆ i64       ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2024-06-1 ┆ NL0011585 ┆ 541       ┆ 4805      ┆ … ┆ Y         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 542       ┆ 4806      ┆ … ┆ Y         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 543       ┆ 4807      ┆ … ┆ Y         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 544       ┆ 4808      ┆ … ┆ Y         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 545       ┆ 4809      ┆ … ┆ Y         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-06-1 ┆ NL0011585 ┆ 739503    ┆ 2108801   ┆ … ┆ N         ┆ N         ┆ Y         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 739504    ┆ 2108802   ┆ … ┆ N         ┆ N         ┆ Y         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 739505    ┆ 2108803   ┆ … ┆ N         ┆ N         ┆ Y         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 739506    ┆ 2108804   ┆ … ┆ N         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-06-1 ┆ NL0011585 ┆ 739801    ┆ 2110783   ┆ … ┆ Y         ┆ N         ┆ N         ┆ N        │
│ 3         ┆ 146       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00:00:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df[1000:1100, :].write_csv("sample.csv")